### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by beaaan** [Cr4xy/agar-lvlgen#39]
/home/trojan/agar-lvlgen/lvlgen.js:39
ttps://raw.githubusercontent.com/Cr4xy/agar-lvlgen/master/version', (res) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by ItzLevvie** [comment]
Use the latest Node 5.

**Comment by beaaan** [comment]
stable

**Comment by ItzLevvie** [comment]
Use LTS.

**Comment by beaaan** [comment]
but last time im using Stable and its working

**Comment by beaaan** [comment]
hmm
