### ISSUE TITLE
Mac OS problem.

### ISSUE THREAD

**Issue by AlhassanKH** [Cr4xy/agar-lvlgen#46]
Hello, according to this video
https://www.youtube.com/watch?v=2M5QwsU41T4
I made the same steps, done everything and Installed everything. 
When I come and drag the lvlgen.js I get this
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Hassan/Downloads/agar-lvlgen-master/lvlgen.js:5:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

I reinstalled and did the same process but whats the deal? I Installed node.js too. 
Is node.js not installed properly or something Is wrong?

**Comment by AlhassanKH** [comment]
Some HOW I fixed It. 
Close please.

**Comment by clairekardas** [comment]
Kk.
Btw your name is Hassan? :D
Lol like our 2. nd dev @hassanilia97

**Comment by Cr4xy** [comment]
Ok. :)
